### ISSUE TITLE
Could not convert string to float error when reading a file

### ISSUE THREAD

**Issue by jnsebgosselin** [cgq-qgc/HydroSensorReader#58]
When trying to read the following file, we get a `could not convert string to float` error.

[1047560_Nouvelle_2019-11-05_CompensatedCompensated.zip](https://github.com/cgq-qgc/HydroSensorReader/files/4477457/1047560_Nouvelle_2019-11-05_CompensatedCompensated.zip)

```python
Traceback (most recent call last):
  File "D:\Projets\HydroSensorReader\hydsensread\file_reader\compagny_file_reader\solinst_file_reader.py", line 585, in _get_data
    values = [float(val[param_col_index]) for val in data]
  File "D:\Projets\HydroSensorReader\hydsensread\file_reader\compagny_file_reader\solinst_file_reader.py", line 585, in <listcomp>
    values = [float(val[param_col_index]) for val in data]
ValueError: could not convert string to float:
```

**Comment by jnsebgosselin** [comment]
Le problème vient du fait que la première données de température est manquante dans la série de données.

![image](https://user-images.githubusercontent.com/10170372/79268848-72bee380-7e69-11ea-82b6-d9f380be294e.png)
